import 'System'
import 'UnityEngine'
import 'PluginsUI'
import 'DG.Tweening'
import 'ITween'
import 'Assembly-CSharp'	-- The user-code assembly generated by Unity.

local Angle = Vector3.up;
local Speed = 5;

local showEnv = false
local envScroll = Vector2.zero

function Awake()   
    --transform:FindChild('Text'):GetComponent('Text').text =  'set text from lua script'
    -- ok text:GetComponent('Text').text   = 'set text from lua script'
    -- ok text.text = 'set text from lua script'
end

function Start()
   --  GameObject.Find("Canvas/Text"):GetComponent("Text").text = "ffdfdasfds";     
   --  GameObject.Find('Canvas/Text'):GetComponent('Text').text = 'set text from lua script'
   --  Debug.Log(GameObject.Find('Canvas/Button'):GetComponent('Button').onClick)
    -- GameObject.Find('Canvas/Button'):GetComponent('Button').onClick:AddListener(function()
    --    GameObject.Find('Canvas/Text'):GetComponent('Text').text = 'Hello'
   -- end)           
  

     GameObject.Instantiate(cube)
     Debug.Log("name====>"..btnObj.gameObject.name)
     EventTriggerListener.Get(btnObj.gameObject).onDown = clicked;
     iTween.MoveTo(btnObj.gameObject, Vector3(100, 100, 0), 4);
end

function clicked()
    Debug.Log("OK")
end

function rotation()
    cube.transform:RotateAround(transform.position,Angle,Speed * Time.deltaTime)    
--	if Input.GetKey(KeyCode.W) then
--		Speed = Speed + 1
--	end
--	if Input.GetKey(KeyCode.S) then
--		Speed = Speed - 1
--	end
--	if Input.GetKey(KeyCode.A) then
--		Angle.z = Angle.z + 1
--	end
--	if Input.GetKey(KeyCode.D) then
--		Angle.z = Angle.z - 1
--	end
end

function Update()
	rotation()
    local b = Sphere.transform.forward;
    Sphere:GetComponent('Rigidbody'):AddForce(Vector3(b.x,b.y * (-10),b.z));
end

function OnGUI()
	
end